''''YOU have to enter here your properly credentials about Twilio'''' 

# You can find SSID in your Twilio Dashboard 
SSID = 'AC97511aba573580dea93b6d667017fd9d' 

#You can find on your Twilio Dashboard 
AUTH_TOKEN = '7eeb796f09df1d059d4af3caa02d6b8b' 

#This is the no. generated by Twilio. You can find this on your Twilio Dashboard FROM_NUMBER = '+18173396173' 

#This is your number. Make sure you are adding +91 in beginning 
TO_NUMBER = '+919479480844' 

#This is your Bolt Cloud account API key 
API_KEY = 'eed9c637-cf6c-4cad-849b-c46282df4946' 

#This is the ID of your Bolt device 
DEVICE_ID = 'BOLT11692220' 

FRAME_SIZE = 10 

MUL_FACTOR = 6
